version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_USER: exampleuser
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432" #Host:Container

    volumes:
     - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: